networks:
  tasenor:
    name: tasenor
    driver: bridge

include:
  - docker-compose-common.yml

volumes:
  tasenor_db:

services:
  tasenor-db:
    container_name: tasenor-db
    build:
      context: databases/bookkeeper
    volumes:
      - tasenor_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-7202}:${DB_PORT:-7202}
    environment:
      NODE_ENV: development
      POSTGRES_MULTIPLE_DATABASES: tasenor,tasenor,IU982ehsa09uh0q:bookkeeper,bookkeeper,Biure80s2rt832:test,test,8ydsyTa63298:demo,demo,oiuewHqw3d
      POSTGRES_PASSWORD: Jow92eygdGYwe3edsoy2
      POSTGRES_USER: root
    command: -p ${DB_PORT:-7202}
    networks:
      - tasenor
