#
# This is for testing container build for publishing containers for actual
# use in staging and production servers. Development should be done using
# directly `turbo` or `pnpm` scripts.
#
version: '3'

volumes:
  tasenor_db:

services:
  tasenor-nginx-proxy:
    container_name: tasenor-nginx-proxy
    build:
      context: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/certs"

  tasenor-db:
    container_name: tasenor-db
    build:
      context: databases/bookkeeper
    volumes:
      - tasenor_db:/var/lib/postgresql/data
    ports:
      - 7202:7202
    environment:
      NODE_ENV: development
      POSTGRES_MULTIPLE_DATABASES: tasenor,tasenor,IU982ehsa09uh0q:bookkeeper,bookkeeper,Biure80s2rt832:test,test,8ydsyTa63298:demo,demo,oiuewHqw3d
      POSTGRES_PASSWORD: Jow92eygdGYwe3edsoy2
      POSTGRES_USER: root
    command: -p 7202

  tasenor-bookkeeper:
    container_name: tasenor-bookkeeper
    build:
      context: apps/bookkeeper
    depends_on:
      - tasenor-bookkeeper-api
    ports:
      - 7204
    environment:
      # TODO: Lot of duplicates vs. env.local
      VAULT_URL: env://
      API_URL: http://tasenor-bookkeeper-api:7205
      UI_API_URL: http://bookkeeper-api.localhost
      API_SITE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImF1ZGllbmNlIjoidWkiLCJvd25lciI6Imh0dHA6Ly9sb2NhbGhvc3Q6NzIwNCIsImZlYXRzIjp7IlNVUEVSVVNFUiI6dHJ1ZX19LCJpYXQiOjE2OTAyMTkwNzMsImV4cCI6NDg0MzgxOTA3MywiYXVkIjoicmVmcmVzaCIsImlzcyI6IlRhc2Vub3IifQ.B-gZD84O7xfuqCHSWS52TzhO6VbP4UdXBzEM2N_GrEY
      NODE_ENV: development
      PORT: 7204
      SECRET: eb53dbcd0f081bfcec68bdf88dce90f2a1d26bd88be8ee49caea74920e35bb3e
      VIRTUAL_HOST: bookkeeper.localhost
      VIRTUAL_PORT: 7204
    command: ./bin/wait-for-it.sh -t 60 -h tasenor-bookkeeper-api -p 7205 -- pnpm run docker

  tasenor-bookkeeper-api:
    container_name: tasenor-bookkeeper-api
    build:
      context: apps/bookkeeper-api
    depends_on:
      - tasenor-db
    ports:
      - 7205
    environment:
      VAULT_URL: env://
      UI_ORIGIN_URL: http://bookkeeper.localhost
      DATABASE_ROOT_PASSWORD: Jow92eygdGYwe3edsoy2
      DATABASE_ROOT_USER: root
      DATABASE_URL: postgresql://bookkeeper:Biure80s2rt832@tasenor-db:7202/bookkeeper
      NODE_ENV: development
      PORT: 7205
      SECRET: eb53dbcd0f081bfcec68bdf88dce90f2a1d26bd88be8ee49caea74920e35bb3e
      VIRTUAL_HOST: bookkeeper-api.localhost
      VIRTUAL_PORT: 7205
    command: pnpm run docker
