#
# This is for testing container build for publishing containers for actual
# use in staging and production servers. Development should be done using
# directly `turbo` or `pnpm` scripts.
#
version: '3'

volumes:
  tasenor_db:

networks:
  tasenor:
    name: tasenor
    driver: bridge

services:
  tasenor-nginx-proxy:
    container_name: tasenor-nginx-proxy
    build:
      context: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/etc/nginx/certs"
    networks:
      - tasenor

  tasenor-db:
    container_name: tasenor-db
    build:
      context: databases/bookkeeper
    volumes:
      - tasenor_db:/var/lib/postgresql/data
    ports:
      - 7202:7202
    environment:
      NODE_ENV: development
      POSTGRES_MULTIPLE_DATABASES: tasenor,tasenor,IU982ehsa09uh0q:bookkeeper,bookkeeper,Biure80s2rt832:test,test,8ydsyTa63298:demo,demo,oiuewHqw3d
      POSTGRES_PASSWORD: Jow92eygdGYwe3edsoy2
      POSTGRES_USER: root
    command: -p 7202
    networks:
      - tasenor

  tasenor-bookkeeper:
    container_name: tasenor-bookkeeper
    build:
      context: apps/bookkeeper
    depends_on:
      - tasenor-bookkeeper-api
    ports:
      - 7204:7204
    environment:
      NODE_ENV: development
      PORT: 7204
      VIRTUAL_HOST: bookkeeper.localhost
      VIRTUAL_PORT: 7204
      INITIAL_PLUGIN_REPOS: ${INITIAL_PLUGIN_REPOS:-npm://@tasenor/common-plugins}
      ID_RSA: ${ID_RSA:-}
      ID_RSA_PUB: ${ID_RSA_PUB:-}
    command: pnpm run docker
    networks:
      - tasenor

  tasenor-bookkeeper-api:
    container_name: tasenor-bookkeeper-api
    build:
      context: apps/bookkeeper-api
    depends_on:
      - tasenor-db
    ports:
      - 7205:7205
    environment:
      DATABASE_ROOT_PASSWORD: Jow92eygdGYwe3edsoy2
      DATABASE_ROOT_USER: root
      DATABASE_URL: postgresql://bookkeeper:Biure80s2rt832@tasenor-db:7202/bookkeeper
      NODE_ENV: development
      PORT: 7205
      VIRTUAL_HOST: bookkeeper-api.localhost
      VIRTUAL_PORT: 7205
      INITIAL_PLUGIN_REPOS: ${INITIAL_PLUGIN_REPOS:-npm://@tasenor/common-plugins}
      ID_RSA: ${ID_RSA:-}
      ID_RSA_PUB: ${ID_RSA_PUB:-}
    command: pnpm run docker
    networks:
      - tasenor

  tasenor-docs:
    container_name: tasenor-docs
    build:
      context: apps/docs
    ports:
      - 7207:7207
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: docs.localhost
      VIRTUAL_PORT: 7207
    networks:
      - tasenor
